package tokenization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewAuthCaptureParams creates a new AuthCaptureParams object
// with the default values initialized.
func NewAuthCaptureParams() *AuthCaptureParams {
	var ()
	return &AuthCaptureParams{}
}

/*AuthCaptureParams contains all the parameters to send to the API endpoint
for the auth capture operation typically these are written to a http.Request
*/
type AuthCaptureParams struct {

	/*AuthCaptureRequest
	  The auth capture request.

	*/
	AuthCaptureRequest models.AuthCaptureRequest
}

// WithAuthCaptureRequest adds the authCaptureRequest to the auth capture params
func (o *AuthCaptureParams) WithAuthCaptureRequest(AuthCaptureRequest models.AuthCaptureRequest) *AuthCaptureParams {
	o.AuthCaptureRequest = AuthCaptureRequest
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *AuthCaptureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.AuthCaptureRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
