package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

// AdvanceSubscriptionReader is a Reader for the AdvanceSubscription structure.
type AdvanceSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *AdvanceSubscriptionReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewAdvanceSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewAdvanceSubscriptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewAdvanceSubscriptionOK creates a AdvanceSubscriptionOK with default headers values
func NewAdvanceSubscriptionOK() *AdvanceSubscriptionOK {
	return &AdvanceSubscriptionOK{}
}

/*AdvanceSubscriptionOK handles this case with default header values.

success
*/
type AdvanceSubscriptionOK struct {
	Payload *models.TimeResponsePagedMetadata
}

func (o *AdvanceSubscriptionOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscription-ID}/advance][%d] advanceSubscriptionOK  %+v", 200, o.Payload)
}

func (o *AdvanceSubscriptionOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimeResponsePagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdvanceSubscriptionDefault creates a AdvanceSubscriptionDefault with default headers values
func NewAdvanceSubscriptionDefault(code int) *AdvanceSubscriptionDefault {
	return &AdvanceSubscriptionDefault{
		_statusCode: code,
	}
}

/*AdvanceSubscriptionDefault handles this case with default header values.

error
*/
type AdvanceSubscriptionDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the advance subscription default response
func (o *AdvanceSubscriptionDefault) Code() int {
	return o._statusCode
}

func (o *AdvanceSubscriptionDefault) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscription-ID}/advance][%d] advanceSubscription default  %+v", o._statusCode, o.Payload)
}

func (o *AdvanceSubscriptionDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
