package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewAvailablePaymentMethodsForSubscriptionParams creates a new AvailablePaymentMethodsForSubscriptionParams object
// with the default values initialized.
func NewAvailablePaymentMethodsForSubscriptionParams() *AvailablePaymentMethodsForSubscriptionParams {
	var (
		orderDefault   string = string("DESC")
		orderByDefault string = string("id")
		recordsDefault int32  = int32(10)
	)
	return &AvailablePaymentMethodsForSubscriptionParams{
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,
	}
}

/*AvailablePaymentMethodsForSubscriptionParams contains all the parameters to send to the API endpoint
for the available payment methods for subscription operation typically these are written to a http.Request
*/
type AvailablePaymentMethodsForSubscriptionParams struct {

	/*Offset
	  The offset from the first subscription to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of subscriptions to return.

	*/
	Records *int32
	/*SubscriptionID*/
	SubscriptionID string
}

// WithOffset adds the offset to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithOffset(offset *int32) *AvailablePaymentMethodsForSubscriptionParams {
	o.Offset = offset
	return o
}

// WithOrder adds the order to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithOrder(order *string) *AvailablePaymentMethodsForSubscriptionParams {
	o.Order = order
	return o
}

// WithOrderBy adds the orderBy to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithOrderBy(orderBy *string) *AvailablePaymentMethodsForSubscriptionParams {
	o.OrderBy = orderBy
	return o
}

// WithOrganizations adds the organizations to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithOrganizations(organizations []string) *AvailablePaymentMethodsForSubscriptionParams {
	o.Organizations = organizations
	return o
}

// WithRecords adds the records to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithRecords(records *int32) *AvailablePaymentMethodsForSubscriptionParams {
	o.Records = records
	return o
}

// WithSubscriptionID adds the subscriptionId to the available payment methods for subscription params
func (o *AvailablePaymentMethodsForSubscriptionParams) WithSubscriptionID(subscriptionId string) *AvailablePaymentMethodsForSubscriptionParams {
	o.SubscriptionID = subscriptionId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *AvailablePaymentMethodsForSubscriptionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
