package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

/*CancelSubscriptionParams contains all the parameters to send to the API endpoint
for the cancel subscription operation typically these are written to a http.Request
*/
type CancelSubscriptionParams struct {

	/*SubscriptionID*/
	SubscriptionID string
	/*SubscriptionCancellation
	  The cancellation request

	*/
	SubscriptionCancellation *models.MutableBillingEntity
}

// WriteToRequest writes these params to a swagger request
func (o *CancelSubscriptionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if o.SubscriptionCancellation == nil {
		o.SubscriptionCancellation = new(models.MutableBillingEntity)
	}

	if err := r.SetBodyParam(o.SubscriptionCancellation); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
