package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// NewCreateSubscriptionParams creates a new CreateSubscriptionParams object
// with the default values initialized.
func NewCreateSubscriptionParams() *CreateSubscriptionParams {
	var ()
	return &CreateSubscriptionParams{}
}

/*CreateSubscriptionParams contains all the parameters to send to the API endpoint
for the create subscription operation typically these are written to a http.Request
*/
type CreateSubscriptionParams struct {

	/*Subscription
	  The subscription object to be updated.

	*/
	Subscription *models.Subscription
}

// WithSubscription adds the subscription to the create subscription params
func (o *CreateSubscriptionParams) WithSubscription(Subscription *models.Subscription) *CreateSubscriptionParams {
	o.Subscription = Subscription
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Subscription == nil {
		o.Subscription = new(models.Subscription)
	}

	if err := r.SetBodyParam(o.Subscription); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
