package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetAllSubscriptionsReader is a Reader for the GetAllSubscriptions structure.
type GetAllSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAllSubscriptionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAllSubscriptionsOK creates a GetAllSubscriptionsOK with default headers values
func NewGetAllSubscriptionsOK() *GetAllSubscriptionsOK {
	return &GetAllSubscriptionsOK{}
}

/*GetAllSubscriptionsOK handles this case with default header values.

success
*/
type GetAllSubscriptionsOK struct {
	Payload *models.SubscriptionPagedMetadata
}

func (o *GetAllSubscriptionsOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions][%d] getAllSubscriptionsOK  %+v", 200, o.Payload)
}

func (o *GetAllSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubscriptionPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSubscriptionsDefault creates a GetAllSubscriptionsDefault with default headers values
func NewGetAllSubscriptionsDefault(code int) *GetAllSubscriptionsDefault {
	return &GetAllSubscriptionsDefault{
		_statusCode: code,
	}
}

/*GetAllSubscriptionsDefault handles this case with default header values.

error
*/
type GetAllSubscriptionsDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get all subscriptions default response
func (o *GetAllSubscriptionsDefault) Code() int {
	return o._statusCode
}

func (o *GetAllSubscriptionsDefault) Error() string {
	return fmt.Sprintf("[GET /subscriptions][%d] getAllSubscriptions default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllSubscriptionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
