package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewRemovePaymentMethodFromSubscriptionParams creates a new RemovePaymentMethodFromSubscriptionParams object
// with the default values initialized.
func NewRemovePaymentMethodFromSubscriptionParams() *RemovePaymentMethodFromSubscriptionParams {
	var ()
	return &RemovePaymentMethodFromSubscriptionParams{}
}

/*RemovePaymentMethodFromSubscriptionParams contains all the parameters to send to the API endpoint
for the remove payment method from subscription operation typically these are written to a http.Request
*/
type RemovePaymentMethodFromSubscriptionParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*PaymentMethodID*/
	PaymentMethodID string
	/*SubscriptionID*/
	SubscriptionID string
}

// WithOrganizations adds the organizations to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithOrganizations(organizations []string) *RemovePaymentMethodFromSubscriptionParams {
	o.Organizations = organizations
	return o
}

// WithPaymentMethodID adds the paymentMethodId to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithPaymentMethodID(paymentMethodId string) *RemovePaymentMethodFromSubscriptionParams {
	o.PaymentMethodID = paymentMethodId
	return o
}

// WithSubscriptionID adds the subscriptionId to the remove payment method from subscription params
func (o *RemovePaymentMethodFromSubscriptionParams) WithSubscriptionID(subscriptionId string) *RemovePaymentMethodFromSubscriptionParams {
	o.SubscriptionID = subscriptionId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *RemovePaymentMethodFromSubscriptionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param payment-method-ID
	if err := r.SetPathParam("payment-method-ID", o.PaymentMethodID); err != nil {
		return err
	}

	// path param subscription-ID
	if err := r.SetPathParam("subscription-ID", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
