package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// DeleteMetadataForRatePlanReader is a Reader for the DeleteMetadataForRatePlan structure.
type DeleteMetadataForRatePlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteMetadataForRatePlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteMetadataForRatePlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteMetadataForRatePlanDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeleteMetadataForRatePlanOK creates a DeleteMetadataForRatePlanOK with default headers values
func NewDeleteMetadataForRatePlanOK() *DeleteMetadataForRatePlanOK {
	return &DeleteMetadataForRatePlanOK{}
}

/*DeleteMetadataForRatePlanOK handles this case with default header values.

success
*/
type DeleteMetadataForRatePlanOK struct {
	Payload models.DynamicMetadata
}

func (o *DeleteMetadataForRatePlanOK) Error() string {
	return fmt.Sprintf("[DELETE /product-rate-plans/{product-rate-plan-ID}/metadata][%d] deleteMetadataForRatePlanOK  %+v", 200, o.Payload)
}

func (o *DeleteMetadataForRatePlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteMetadataForRatePlanDefault creates a DeleteMetadataForRatePlanDefault with default headers values
func NewDeleteMetadataForRatePlanDefault(code int) *DeleteMetadataForRatePlanDefault {
	return &DeleteMetadataForRatePlanDefault{
		_statusCode: code,
	}
}

/*DeleteMetadataForRatePlanDefault handles this case with default header values.

error
*/
type DeleteMetadataForRatePlanDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the delete metadata for rate plan default response
func (o *DeleteMetadataForRatePlanDefault) Code() int {
	return o._statusCode
}

func (o *DeleteMetadataForRatePlanDefault) Error() string {
	return fmt.Sprintf("[DELETE /product-rate-plans/{product-rate-plan-ID}/metadata][%d] deleteMetadataForRatePlan default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteMetadataForRatePlanDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
