package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

// GetProductRatePlanByIDReader is a Reader for the GetProductRatePlanByID structure.
type GetProductRatePlanByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetProductRatePlanByIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProductRatePlanByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetProductRatePlanByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetProductRatePlanByIDOK creates a GetProductRatePlanByIDOK with default headers values
func NewGetProductRatePlanByIDOK() *GetProductRatePlanByIDOK {
	return &GetProductRatePlanByIDOK{}
}

/*GetProductRatePlanByIDOK handles this case with default header values.

success
*/
type GetProductRatePlanByIDOK struct {
	Payload *models.ProductRatePlanPagedMetadata
}

func (o *GetProductRatePlanByIDOK) Error() string {
	return fmt.Sprintf("[GET /product-rate-plans/{product-rate-plan-ID}][%d] getProductRatePlanByIdOK  %+v", 200, o.Payload)
}

func (o *GetProductRatePlanByIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductRatePlanPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProductRatePlanByIDDefault creates a GetProductRatePlanByIDDefault with default headers values
func NewGetProductRatePlanByIDDefault(code int) *GetProductRatePlanByIDDefault {
	return &GetProductRatePlanByIDDefault{
		_statusCode: code,
	}
}

/*GetProductRatePlanByIDDefault handles this case with default header values.

error
*/
type GetProductRatePlanByIDDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get product rate plan by ID default response
func (o *GetProductRatePlanByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetProductRatePlanByIDDefault) Error() string {
	return fmt.Sprintf("[GET /product-rate-plans/{product-rate-plan-ID}][%d] getProductRatePlanByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetProductRatePlanByIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
