package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewGetRatePlanByProductAndRatePlanParams creates a new GetRatePlanByProductAndRatePlanParams object
// with the default values initialized.
func NewGetRatePlanByProductAndRatePlanParams() *GetRatePlanByProductAndRatePlanParams {
	var (
		orderDefault   string = string("DESC")
		orderByDefault string = string("created")
		recordsDefault int32  = int32(10)
	)
	return &GetRatePlanByProductAndRatePlanParams{
		Order:   &orderDefault,
		OrderBy: &orderByDefault,
		Records: &recordsDefault,
	}
}

/*GetRatePlanByProductAndRatePlanParams contains all the parameters to send to the API endpoint
for the get rate plan by product and rate plan operation typically these are written to a http.Request
*/
type GetRatePlanByProductAndRatePlanParams struct {

	/*IncludeRetired
	  Whether retired products should be returned.

	*/
	IncludeRetired *bool
	/*Offset
	  The offset from the first product-rate-plan to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*ProductID*/
	ProductID string
	/*RatePlanID*/
	RatePlanID string
	/*Records
	  The maximum number of product-rate-plans to return.

	*/
	Records *int32
}

// WithIncludeRetired adds the includeRetired to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithIncludeRetired(includeRetired *bool) *GetRatePlanByProductAndRatePlanParams {
	o.IncludeRetired = includeRetired
	return o
}

// WithOffset adds the offset to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithOffset(offset *int32) *GetRatePlanByProductAndRatePlanParams {
	o.Offset = offset
	return o
}

// WithOrder adds the order to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithOrder(order *string) *GetRatePlanByProductAndRatePlanParams {
	o.Order = order
	return o
}

// WithOrderBy adds the orderBy to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithOrderBy(orderBy *string) *GetRatePlanByProductAndRatePlanParams {
	o.OrderBy = orderBy
	return o
}

// WithOrganizations adds the organizations to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithOrganizations(organizations []string) *GetRatePlanByProductAndRatePlanParams {
	o.Organizations = organizations
	return o
}

// WithProductID adds the productId to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithProductID(productId string) *GetRatePlanByProductAndRatePlanParams {
	o.ProductID = productId
	return o
}

// WithRatePlanID adds the ratePlanId to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithRatePlanID(ratePlanId string) *GetRatePlanByProductAndRatePlanParams {
	o.RatePlanID = ratePlanId
	return o
}

// WithRecords adds the records to the get rate plan by product and rate plan params
func (o *GetRatePlanByProductAndRatePlanParams) WithRecords(records *int32) *GetRatePlanByProductAndRatePlanParams {
	o.Records = records
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetRatePlanByProductAndRatePlanParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.IncludeRetired != nil {

		// query param include_retired
		var qrIncludeRetired bool
		if o.IncludeRetired != nil {
			qrIncludeRetired = *o.IncludeRetired
		}
		qIncludeRetired := swag.FormatBool(qrIncludeRetired)
		if qIncludeRetired != "" {
			if err := r.SetQueryParam("include_retired", qIncludeRetired); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param product-ID
	if err := r.SetPathParam("product-ID", o.ProductID); err != nil {
		return err
	}

	// path param rate-plan-ID
	if err := r.SetPathParam("rate-plan-ID", o.RatePlanID); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
