package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetRatePlanByProductReader is a Reader for the GetRatePlanByProduct structure.
type GetRatePlanByProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetRatePlanByProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRatePlanByProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetRatePlanByProductDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetRatePlanByProductOK creates a GetRatePlanByProductOK with default headers values
func NewGetRatePlanByProductOK() *GetRatePlanByProductOK {
	return &GetRatePlanByProductOK{}
}

/*GetRatePlanByProductOK handles this case with default header values.

success
*/
type GetRatePlanByProductOK struct {
	Payload *models.ProductRatePlanPagedMetadata
}

func (o *GetRatePlanByProductOK) Error() string {
	return fmt.Sprintf("[GET /product-rate-plans/product/{product-ID}][%d] getRatePlanByProductOK  %+v", 200, o.Payload)
}

func (o *GetRatePlanByProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductRatePlanPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRatePlanByProductDefault creates a GetRatePlanByProductDefault with default headers values
func NewGetRatePlanByProductDefault(code int) *GetRatePlanByProductDefault {
	return &GetRatePlanByProductDefault{
		_statusCode: code,
	}
}

/*GetRatePlanByProductDefault handles this case with default header values.

error
*/
type GetRatePlanByProductDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get rate plan by product default response
func (o *GetRatePlanByProductDefault) Code() int {
	return o._statusCode
}

func (o *GetRatePlanByProductDefault) Error() string {
	return fmt.Sprintf("[GET /product-rate-plans/product/{product-ID}][%d] getRatePlanByProduct default  %+v", o._statusCode, o.Payload)
}

func (o *GetRatePlanByProductDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
