package product_rate_plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new product rate plans API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for product rate plans API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*Returns a collection of product-rate-plans. By default 10 values are returned. Records are returned in natural order.

{"nickname":"Get all rate-plans","response":"getPRPAll.html"}
*/
func (a *Client) GetAllRatePlans(params GetAllRatePlansParams) (*GetAllRatePlansOK, error) {
	// TODO: Validate the params before sending

	result, err := a.transport.Submit(&client.Operation{
		ID:     "getAllRatePlans",
		Params: &params,
		Reader: &GetAllRatePlansReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAllRatePlansOK), nil
}

/*Returns product-rate-plans, specified by the product-rate-plan id or name.

{"nickname":"Retrieve an existing rate-plan","response":"getPRPByID.html"}
*/
func (a *Client) GetProductRatePlanByID(params GetProductRatePlanByIDParams) (*GetProductRatePlanByIDOK, error) {
	// TODO: Validate the params before sending

	result, err := a.transport.Submit(&client.Operation{
		ID:     "getProductRatePlanByID",
		Params: &params,
		Reader: &GetProductRatePlanByIDReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetProductRatePlanByIDOK), nil
}

/*Returns a collection of product-rate-plans, specified by the product-ID parameter. By default 10 values are returned. Records are returned in natural order.

{"nickname":"Retrieve by product","response":"getPRPByProductID.html"}
*/
func (a *Client) GetRatePlanByProduct(params GetRatePlanByProductParams) (*GetRatePlanByProductOK, error) {
	// TODO: Validate the params before sending

	result, err := a.transport.Submit(&client.Operation{
		ID:     "getRatePlanByProduct",
		Params: &params,
		Reader: &GetRatePlanByProductReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRatePlanByProductOK), nil
}

/*Returns a collection of product-rate-plans, specified by the product-ID parameter. By default 10 values are returned. Records are returned in natural order.

{"nickname":"Retrieve by name","response":"getPRPByNameAndProduct.html"}
*/
func (a *Client) GetRatePlanByProductAndRatePlan(params GetRatePlanByProductAndRatePlanParams) (*GetRatePlanByProductAndRatePlanOK, error) {
	// TODO: Validate the params before sending

	result, err := a.transport.Submit(&client.Operation{
		ID:     "getRatePlanByProductAndRatePlan",
		Params: &params,
		Reader: &GetRatePlanByProductAndRatePlanReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRatePlanByProductAndRatePlanOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}

// NewAPIError creates a new API error
func NewAPIError(opName string, response interface{}, code int) APIError {
	return APIError{
		OperationName: opName,
		Response:      response,
		Code:          code,
	}
}

// APIError wraps an error model and captures the status code
type APIError struct {
	OperationName string
	Response      interface{}
	Code          int
}

func (a APIError) Error() string {
	return fmt.Sprintf("%s (status %d): %+v ", a.OperationName, a.Code, a.Response)
}
