package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPaymentByIDParams creates a new GetPaymentByIDParams object
// with the default values initialized.
func NewGetPaymentByIDParams() *GetPaymentByIDParams {
	var ()
	return &GetPaymentByIDParams{}
}

/*GetPaymentByIDParams contains all the parameters to send to the API endpoint
for the get payment by ID operation typically these are written to a http.Request
*/
type GetPaymentByIDParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*PaymentID
	  The unique string-ID of the payment.

	*/
	PaymentID string
}

// WithOrganizations adds the organizations to the get payment by ID params
func (o *GetPaymentByIDParams) WithOrganizations(Organizations []string) *GetPaymentByIDParams {
	o.Organizations = Organizations
	return o
}

// WithPaymentID adds the paymentId to the get payment by ID params
func (o *GetPaymentByIDParams) WithPaymentID(PaymentID string) *GetPaymentByIDParams {
	o.PaymentID = PaymentID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param payment-ID
	if err := r.SetPathParam("payment-ID", o.PaymentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
