package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetAllPaymentsReader is a Reader for the GetAllPayments structure.
type GetAllPaymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllPaymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllPaymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAllPaymentsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAllPaymentsOK creates a GetAllPaymentsOK with default headers values
func NewGetAllPaymentsOK() *GetAllPaymentsOK {
	return &GetAllPaymentsOK{}
}

/*GetAllPaymentsOK handles this case with default header values.

success
*/
type GetAllPaymentsOK struct {
	Payload *models.PaymentPagedMetadata
}

func (o *GetAllPaymentsOK) Error() string {
	return fmt.Sprintf("[GET /payments][%d] getAllPaymentsOK  %+v", 200, o.Payload)
}

func (o *GetAllPaymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllPaymentsDefault creates a GetAllPaymentsDefault with default headers values
func NewGetAllPaymentsDefault(code int) *GetAllPaymentsDefault {
	return &GetAllPaymentsDefault{
		_statusCode: code,
	}
}

/*GetAllPaymentsDefault handles this case with default header values.

error
*/
type GetAllPaymentsDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get all payments default response
func (o *GetAllPaymentsDefault) Code() int {
	return o._statusCode
}

func (o *GetAllPaymentsDefault) Error() string {
	return fmt.Sprintf("[GET /payments][%d] getAllPayments default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllPaymentsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
