package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

type GetPaymentByIDReader struct {
	formats strfmt.Registry
}

func (o *GetPaymentByIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPaymentByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetPaymentByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetPaymentByIDOK creates a GetPaymentByIDOK with default headers values
func NewGetPaymentByIDOK() *GetPaymentByIDOK {
	return &GetPaymentByIDOK{}
}

/*GetPaymentByIDOK

success
*/
type GetPaymentByIDOK struct {
	Payload *models.PaymentPagedMetadata
}

func (o *GetPaymentByIDOK) Error() string {
	return fmt.Sprintf("[GET /payments/{payment-ID}][%d] getPaymentByIdOK  %+v", 200, o.Payload)
}

func (o *GetPaymentByIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPaymentByIDDefault creates a GetPaymentByIDDefault with default headers values
func NewGetPaymentByIDDefault(code int) *GetPaymentByIDDefault {
	return &GetPaymentByIDDefault{
		_statusCode: code,
	}
}

/*GetPaymentByIDDefault

error
*/
type GetPaymentByIDDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get payment by ID default response
func (o *GetPaymentByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetPaymentByIDDefault) Error() string {
	return fmt.Sprintf("[GET /payments/{payment-ID}][%d] getPaymentByID default  %+v", o._statusCode, o.Payload)
}

func (o *GetPaymentByIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
