package payment_methods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePaymentMethodParams creates a new DeletePaymentMethodParams object
// with the default values initialized.
func NewDeletePaymentMethodParams() *DeletePaymentMethodParams {
	var ()
	return &DeletePaymentMethodParams{}
}

/*DeletePaymentMethodParams contains all the parameters to send to the API endpoint
for the delete payment method operation typically these are written to a http.Request
*/
type DeletePaymentMethodParams struct {

	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*PaymentMethodID*/
	PaymentMethodID string
}

// WithOrganizations adds the organizations to the delete payment method params
func (o *DeletePaymentMethodParams) WithOrganizations(Organizations []string) *DeletePaymentMethodParams {
	o.Organizations = Organizations
	return o
}

// WithPaymentMethodID adds the paymentMethodId to the delete payment method params
func (o *DeletePaymentMethodParams) WithPaymentMethodID(PaymentMethodID string) *DeletePaymentMethodParams {
	o.PaymentMethodID = PaymentMethodID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePaymentMethodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	// path param payment-method-ID
	if err := r.SetPathParam("payment-method-ID", o.PaymentMethodID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
