package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/authclub/billforward/models"
)

// GetProfileReader is a Reader for the GetProfile structure.
type GetProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetProfileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetProfileOK creates a GetProfileOK with default headers values
func NewGetProfileOK() *GetProfileOK {
	return &GetProfileOK{}
}

/*GetProfileOK handles this case with default header values.

success
*/
type GetProfileOK struct {
	Payload *models.ProfilePagedMetadata
}

func (o *GetProfileOK) Error() string {
	return fmt.Sprintf("[GET /profiles/{profile-ID}][%d] getProfileOK  %+v", 200, o.Payload)
}

func (o *GetProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProfilePagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfileDefault creates a GetProfileDefault with default headers values
func NewGetProfileDefault(code int) *GetProfileDefault {
	return &GetProfileDefault{
		_statusCode: code,
	}
}

/*GetProfileDefault handles this case with default header values.

error
*/
type GetProfileDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get profile default response
func (o *GetProfileDefault) Code() int {
	return o._statusCode
}

func (o *GetProfileDefault) Error() string {
	return fmt.Sprintf("[GET /profiles/{profile-ID}][%d] getProfile default  %+v", o._statusCode, o.Payload)
}

func (o *GetProfileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
