package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

// NewUpdateProfileParams creates a new UpdateProfileParams object
// with the default values initialized.
func NewUpdateProfileParams() *UpdateProfileParams {
	var ()
	return &UpdateProfileParams{}
}

/*UpdateProfileParams contains all the parameters to send to the API endpoint
for the update profile operation typically these are written to a http.Request
*/
type UpdateProfileParams struct {

	/*Request
	  The profile object to be updated.

	*/
	Request *models.UpdateProfileRequest
}

// WithRequest adds the request to the update profile params
func (o *UpdateProfileParams) WithRequest(request *models.UpdateProfileRequest) *UpdateProfileParams {
	o.Request = request
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProfileParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Request == nil {
		o.Request = new(models.UpdateProfileRequest)
	}

	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
