package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"
)

// NewDeleteMetadataForAccountParams creates a new DeleteMetadataForAccountParams object
// with the default values initialized.
func NewDeleteMetadataForAccountParams() *DeleteMetadataForAccountParams {
	var ()
	return &DeleteMetadataForAccountParams{}
}

/*DeleteMetadataForAccountParams contains all the parameters to send to the API endpoint
for the delete metadata for account operation typically these are written to a http.Request
*/
type DeleteMetadataForAccountParams struct {

	/*AccountID*/
	AccountID string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
}

// WithAccountID adds the accountId to the delete metadata for account params
func (o *DeleteMetadataForAccountParams) WithAccountID(accountId string) *DeleteMetadataForAccountParams {
	o.AccountID = accountId
	return o
}

// WithOrganizations adds the organizations to the delete metadata for account params
func (o *DeleteMetadataForAccountParams) WithOrganizations(organizations []string) *DeleteMetadataForAccountParams {
	o.Organizations = organizations
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMetadataForAccountParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param account-ID
	if err := r.SetPathParam("account-ID", o.AccountID); err != nil {
		return err
	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
