package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllAccountsParams creates a new GetAllAccountsParams object
// with the default values initialized.
func NewGetAllAccountsParams() *GetAllAccountsParams {
	var (
		includeRetiredDefault bool   = bool(true)
		offsetDefault         int32  = int32(0)
		orderDefault          string = string("DESC")
		orderByDefault        string = string("created")
		recordsDefault        int32  = int32(10)
		usersOnlyDefault      bool   = bool(false)
	)
	return &GetAllAccountsParams{
		IncludeRetired: &includeRetiredDefault,
		Offset:         &offsetDefault,
		Order:          &orderDefault,
		OrderBy:        &orderByDefault,
		Records:        &recordsDefault,
		UsersOnly:      &usersOnlyDefault,
	}
}

/*GetAllAccountsParams contains all the parameters to send to the API endpoint
for the get all accounts operation typically these are written to a http.Request
*/
type GetAllAccountsParams struct {

	/*ID
	  A list of account IDs used to filter the output.

	*/
	ID []string
	/*IncludeRetired
	  Whether retired products should be returned.

	*/
	IncludeRetired *bool
	/*Metadata*/
	Metadata *string
	/*Offset
	  The offset from the first taxation-link to return.

	*/
	Offset *int32
	/*Order
	  Ihe direction of any ordering, either ASC or DESC.

	*/
	Order *string
	/*OrderBy
	  Specify a field used to order the result set.

	*/
	OrderBy *string
	/*Organizations
	  A list of organization-IDs used to restrict the scope of API calls.

	*/
	Organizations []string
	/*Records
	  The maximum number of taxation-links to return.

	*/
	Records *int32
	/*UsersOnly
	  Whether only accounts have a user should be returned.

	*/
	UsersOnly *bool
}

// WithID adds the id to the get all accounts params
func (o *GetAllAccountsParams) WithID(ID []string) *GetAllAccountsParams {
	o.ID = ID
	return o
}

// WithIncludeRetired adds the includeRetired to the get all accounts params
func (o *GetAllAccountsParams) WithIncludeRetired(IncludeRetired *bool) *GetAllAccountsParams {
	o.IncludeRetired = IncludeRetired
	return o
}

// WithMetadata adds the metadata to the get all accounts params
func (o *GetAllAccountsParams) WithMetadata(Metadata *string) *GetAllAccountsParams {
	o.Metadata = Metadata
	return o
}

// WithOffset adds the offset to the get all accounts params
func (o *GetAllAccountsParams) WithOffset(Offset *int32) *GetAllAccountsParams {
	o.Offset = Offset
	return o
}

// WithOrder adds the order to the get all accounts params
func (o *GetAllAccountsParams) WithOrder(Order *string) *GetAllAccountsParams {
	o.Order = Order
	return o
}

// WithOrderBy adds the orderBy to the get all accounts params
func (o *GetAllAccountsParams) WithOrderBy(OrderBy *string) *GetAllAccountsParams {
	o.OrderBy = OrderBy
	return o
}

// WithOrganizations adds the organizations to the get all accounts params
func (o *GetAllAccountsParams) WithOrganizations(Organizations []string) *GetAllAccountsParams {
	o.Organizations = Organizations
	return o
}

// WithRecords adds the records to the get all accounts params
func (o *GetAllAccountsParams) WithRecords(Records *int32) *GetAllAccountsParams {
	o.Records = Records
	return o
}

// WithUsersOnly adds the usersOnly to the get all accounts params
func (o *GetAllAccountsParams) WithUsersOnly(UsersOnly *bool) *GetAllAccountsParams {
	o.UsersOnly = UsersOnly
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAccountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	valuesID := o.ID

	joinedID := swag.JoinByFormat(valuesID, "multi")
	// query array param id
	if err := r.SetQueryParam("id", joinedID...); err != nil {
		return err
	}

	if o.IncludeRetired != nil {

		// query param include_retired
		var qrIncludeRetired bool
		if o.IncludeRetired != nil {
			qrIncludeRetired = *o.IncludeRetired
		}
		qIncludeRetired := swag.FormatBool(qrIncludeRetired)
		if qIncludeRetired != "" {
			if err := r.SetQueryParam("include_retired", qIncludeRetired); err != nil {
				return err
			}
		}

	}

	if o.Metadata != nil {

		// query param metadata
		var qrMetadata string
		if o.Metadata != nil {
			qrMetadata = *o.Metadata
		}
		qMetadata := qrMetadata
		if qMetadata != "" {
			if err := r.SetQueryParam("metadata", qMetadata); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string
		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {
			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}

	}

	valuesOrganizations := o.Organizations

	joinedOrganizations := swag.JoinByFormat(valuesOrganizations, "multi")
	// query array param organizations
	if err := r.SetQueryParam("organizations", joinedOrganizations...); err != nil {
		return err
	}

	if o.Records != nil {

		// query param records
		var qrRecords int32
		if o.Records != nil {
			qrRecords = *o.Records
		}
		qRecords := swag.FormatInt32(qrRecords)
		if qRecords != "" {
			if err := r.SetQueryParam("records", qRecords); err != nil {
				return err
			}
		}

	}

	if o.UsersOnly != nil {

		// query param users_only
		var qrUsersOnly bool
		if o.UsersOnly != nil {
			qrUsersOnly = *o.UsersOnly
		}
		qUsersOnly := swag.FormatBool(qrUsersOnly)
		if qUsersOnly != "" {
			if err := r.SetQueryParam("users_only", qUsersOnly); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
