package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/authclub/billforward/models"
)

// GetAllAccountsReader is a Reader for the GetAllAccounts structure.
type GetAllAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAllAccountsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetAllAccountsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetAllAccountsOK creates a GetAllAccountsOK with default headers values
func NewGetAllAccountsOK() *GetAllAccountsOK {
	return &GetAllAccountsOK{}
}

/*GetAllAccountsOK handles this case with default header values.

success
*/
type GetAllAccountsOK struct {
	Payload *models.AccountPagedMetadata
}

func (o *GetAllAccountsOK) Error() string {
	return fmt.Sprintf("[GET /accounts][%d] getAllAccountsOK  %+v", 200, o.Payload)
}

func (o *GetAllAccountsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountPagedMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllAccountsDefault creates a GetAllAccountsDefault with default headers values
func NewGetAllAccountsDefault(code int) *GetAllAccountsDefault {
	return &GetAllAccountsDefault{
		_statusCode: code,
	}
}

/*GetAllAccountsDefault handles this case with default header values.

error
*/
type GetAllAccountsDefault struct {
	_statusCode int

	Payload *models.BFError
}

// Code gets the status code for the get all accounts default response
func (o *GetAllAccountsDefault) Code() int {
	return o._statusCode
}

func (o *GetAllAccountsDefault) Error() string {
	return fmt.Sprintf("[GET /accounts][%d] getAllAccounts default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllAccountsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BFError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
